### ISSUE TITLE
Commit message validation

### ISSUE THREAD

**Issue by dmfs** [dmfs/gver#79]
In some cases commit message must have very specific formats (e.g. conventional commits) or need to contain certain information (e.g. a ticket number).
Maybe add another `fail` change type that just errors when it matches.

**Comment by dmfs** [comment]
Idea, call the change type `invalid` so it looks like
```groovy
gver {
    changes {
        are invalid when {
            commitMessage not(contains(~/#(?<issue>[A-Z]{2,6}-\d+)\b/) {  // all commits must refer to an existing Jira issue
                where("issue") { isIssue { true } } 
            }
        }
        are major ....
    }
}
```

**Comment by sschuberth** [comment]
I was about to ask for exactly this feature 😀 Because as regex are anyway already defined (in order to determine the issue type), it makes sense to reuse those definitions to also check for (in-)valid commits.

However, as projects may be only switched to e.g. Conventional Commits at a certain point in time, probably not all of the Git history should be checked, but only commits starting from a certain / the latest tag, or an explicitly given commit.

**Comment by dmfs** [comment]
Right, the plugin only evaluates commits up to the most recent version tag. So the history won't be taken into account.
